---
- hosts: "all"
  remote_user: "root"
  become: true
  become_user: "root"
  become_method: "sudo"
  force_handlers: true
  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
         
  roles:
    - role: geerlingguy.docker
      vars:
        - docker_install_compose: true

  tasks:
    - name: "test hallo"
      shell: "echo hello"

